config/routes.rb
Rails.application.routes.draw do
  resources :users, :locations, :interests, :link_ups, :user_interests
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :user_interests
  has_many :users, through: :user_interests

end

app/models/link_up.rb
class LinkUp < ApplicationRecord
  belongs_to :user_guest
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :link_ups
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i


  has_many :user_guests
  has_many :guests, through: :user_guests
  has_many :user_interests
  has_many :interests, through: :user_interests

end

app/models/user_guest.rb
class UserGuest < ApplicationRecord
  belongs_to :user
  belongs_to :guest, class_name: "User"
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def index
    @interests = Interest.all
    @search_interests = Interest.where("name LIKE ? ", "%#{params[:search]}%")
  end

  def show
    @interest = Interest.find(params[:id])
  end

  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.create
    if @interest.valid?
      redirect_to @interest
    else
      flash[:errors] = @interest.errors.full_messages
      redirect_to new_interest_path
    end
  end

  def edit
    @interest = Interest.find(params[:id])

  end

  def update
    @interest = Interest.find(params[:id])

  end

  def destroy
    @interest = Interest.find(params[:id])
  end

  def search
  end
  private

  def interest_params
    params.require(:interest).permit(:name)
  end

end

app/controllers/link_ups_controller.rb
class LinkUpsController < ApplicationController
  def index
  end
  
  def show
    @link_up = LinkUp.find(params[:id])
    @location =  Location.find(@link_up.location_id)
    @user = User.find(@link_up.user_id)
    @interest = Interest.find(@link_up.interest_id)
    @guest = User.find(@link_up.guest_id)
  end

  def new
    @link_up = LinkUp.new
    @locations = Location.all
    @interests = Interest.all
    @users = User.all
  end

  def create
    @link_up = LinkUp.create(link_up_params)
    if @link_up.valid?
      redirect_to @link_up
    end
  end

  # def edit
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

  def link_up_params
    params.require(:link_up).permit(:id, :name, :location_id, :interest_id, :user_id, :guest_id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController

  def index
    @user_interests = UserInterest.all
  end

  def new
    @user_interest = UserInterest.new
    @interests = Interest.all
  end

  def create
    @user_interest = UserInterest.create(user_interest_params)
    if @user_interest.valid?
      redirect_to @user_interest
    end
  end

  def show
    @user_interest = UserInterest.find(params[:id])
  end

  private

  def user_interest_params
    params.require(:user_interest).permit(:user_id, :interest_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @interests = Interest.all
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to new_user_interest_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
    @interests = Interest.all
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :datetime, :email, interest_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/link_ups_helper.rb
module LinkUpsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_interests_helper.rb
module UserInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/interests/destroy.html.erb
<h1>Interests#destroy</h1>
<p>Find me in app/views/interests/destroy.html.erb</p>

app/views/interests/edit.html.erb
<h1>Interests#edit</h1>
<p>Find me in app/views/interests/edit.html.erb</p>

app/views/interests/index.html.erb
<h1>Interests#index</h1>

<!-- <% @interests.each do |i| %>
  <ul>
    <li> <%= i.name %> </li>
  </ul>
<% end %> -->

<p>Search for guests with similiar interests</p>

<%= form_tag interests_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Type your interest here" %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<br>

app/views/interests/new.html.erb
<%= render "errors/flash_errors" %>

<h1>New Interest</h1>
<%= form_for @interest do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/interests/show.html.erb
<%= @interest.name %>

<br />

app/views/interests/update.html.erb
<h1>Interests#update</h1>
<p>Find me in app/views/interests/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkup</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app_container">


    <%= yield %>
    </div>
  </body>
</html>

app/views/link_ups/edit.html.erb
<h1>LinkUps#edit</h1>
<p>Find me in app/views/link_ups/edit.html.erb</p>

app/views/link_ups/index.html.erb
<h1>Available Locations for Linkups</h1>

<ul>
  <% @locations.each do |location| %>
  <li> <%= link_to location.name, location.link_ups, {:class => 'sml_btn'} %> </li>
  <% end %>
</ul>

app/views/link_ups/new.html.erb
<div class="form_container">

<h1>Forge a Link-Up!</h1>

<%= form_for @link_up do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Name this LinkUp!" %>
</div>

<div class="">
  <%= f.label :user_id %>
  <%= f.text_field :user_id, placeholder: "Enter user id(for now)" %>
</div>

<div class="">
  <%= f.label "location"%>
  <%= f.collection_select(:location_id, @locations, :id, :name) %>
</div>

<div class="">
  <%= f.label "interest"%>
  <%= f.collection_select(:interest_id, @interests, :id, :name) %>
</div>

<div class="">
  <%= f.label "guest"%>
  <%= f.collection_select(:guest_id, @users, :id, :first_name) %>
</div>


<!-- will need add guest button to add to linkup -->

  <%= f.submit %>
<% end %>
</div>

app/views/link_ups/show.html.erb
<h1> Great job <%= @user.first_name %>! You created the <%= @link_up.name %> LinkUp!</h1><br>
<h3> It will be in <%= @location.name%> with</h3>
<h1> <%= @guest.first_name %></h1>
<h3> Because, well, you are both interested in <%= @interest.name %>.</h3>

app/views/link_ups/update.html.erb
<h1>LinkUps#update</h1>
<p>Find me in app/views/link_ups/update.html.erb</p>

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/destroy.html.erb
<h1>Locations#destroy</h1>
<p>Find me in app/views/locations/destroy.html.erb</p>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/user_interests/create.html.erb
<h1>UserInterests#create</h1>
<p>Find me in app/views/user_interests/create.html.erb</p>

app/views/user_interests/destroy.html.erb
<h1>UserInterests#destroy</h1>
<p>Find me in app/views/user_interests/destroy.html.erb</p>

app/views/user_interests/edit.html.erb
<h1>UserInterests#edit</h1>
<p>Find me in app/views/user_interests/edit.html.erb</p>

app/views/user_interests/index.html.erb
<h1>UserInterests#index</h1>
<p>Find me in app/views/user_interests/index.html.erb</p>
<% @user_interests.each do |i| %>
  <ul>
    <% if i.interest.name == "Crime Fighting" %>
    <li><%= i.user.first_name %></li>
    <% end %>
  </ul>
<% end %>

app/views/user_interests/new.html.erb
<h1>User Interests</h1>
<p>Find me in app/views/user_interests/new.html.erb</p>
<div class="select_menu">
  <%= form_for @user_interest do |f|%>
  <%= f.label 'Enter user Id: ' %>
  <%= f.text_field :user_id  %>

  <%= f.label 'Please select Interest: ' %>
  <%= f.collection_select :interest_id, @interests, :id, :name  %>
</div>
<%= f.submit :class => 'big_button' %>
<% end %>

app/views/user_interests/show.html.erb
<h1>UserInterests#show</h1>
<p><%= @user_interest.user.first_name %></p>

app/views/user_interests/update.html.erb
<h1>UserInterests#update</h1>
<p>Find me in app/views/user_interests/update.html.erb</p>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/new.html.erb
<%= render "errors/flash_errors" %>

<div class="form_container">
  <h1>New User</h1>

  <%= form_for @user do |f| %>
<div>
  <%= f.label :first_name %> :<br>
  <%= f.text_field :first_name %>
</div>
  <div>
    <%= f.label :last_name %> :<br>
    <%= f.text_field :last_name %>
  </div>
    <div>
      <%= f.label :username %> :<br>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :email %> :<br>
      <%= f.text_field :email %>


    </div>
    <div class="select_menu">
      <%= f.label 'Please select Interest: ' %>
      <%= f.collection_select :interest_ids, @interests, :id, :name  %>
    </div>
    <%= f.submit :class => 'big_button' %>
  <% end %>
  </div>

app/views/users/show.html.erb
<h2><%= @user.first_name %> <%= @user.last_name %>
  </h2>
  <div>
    <p> <%= @user.username %> </p>
    <p> <%= @user.email %> </p>
  </div>

  <p> <%= link_to "Create Link Up", new_link_up_path, {:class => "sml_btn"}  %> </p>
  <p> <%= link_to "Find Link Up", link_ups_path, {:class => "sml_btn"} %> </p>

<% if !@user.interests.empty? %>
  <h3>Interests</h3>
  <ul>
    <% @user.interests.each do |interest| %>
      <li><%= link_to interest.name, interest %></li>
    <% end %>
  </ul>
<% end %>

<% if @user.link_ups.length > 0 %>
  <h3>Link Ups</h3>
  <ul>
    <% @user.link_ups.each do |link_up| %>
      <li><%= link_to link_up.name, link_up %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>